"""Export the compiled LangGraph pipeline as Mermaid (spec §4.1).

Run:  python scripts/export_graph.py            # write docs/architecture.md
      python scripts/export_graph.py --check    # exit 1 if the committed file is stale (CI)
"""

import argparse
import sys
from pathlib import Path

from atlas.config import Settings

DOCS = Path("docs/architecture.md")


def render() -> str:
    from atlas.pipeline.graph import build_graph_runner

    # Structure-only: no models, no network — nodes are never executed for export.
    runner = build_graph_runner(retriever=None, llm=None, settings=Settings(_env_file=None))
    mermaid = runner._app.get_graph().draw_mermaid()
    return (
        "# Architecture\n\n"
        "Live graph of the atlas-rag query pipeline (auto-generated by\n"
        "`scripts/export_graph.py` from the compiled LangGraph — do not edit by hand;\n"
        "CI fails when this file is stale).\n\n"
        "```mermaid\n"
        f"{mermaid}\n"
        "```\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed doc is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not DOCS.exists() or DOCS.read_text(encoding="utf-8") != content:
            print("docs/architecture.md is stale — run: python scripts/export_graph.py")
            sys.exit(1)
        print("architecture diagram up to date")
        return
    DOCS.parent.mkdir(parents=True, exist_ok=True)
    DOCS.write_text(content, encoding="utf-8")
    print(f"wrote {DOCS}")


if __name__ == "__main__":
    main()
